### ISSUE TITLE
A 5-letter word was picked, but site prompted to guess a 4-letter word

### ISSUE THREAD

**Issue by LaVashikk** [HugoBDesigner/Portle#13]
![image](https://github.com/HugoBDesigner/Portle/assets/105387234/7304c09d-8ecc-4b2c-9f46-28b7736f0f49)
Tbh, I don't even know how to comment on it ¯\\\_(ツ)\_/¯

**Comment by HugoBDesigner** [comment]
Actually, the game lets you guess words of size anywhere between 4 and 10 characters. The size of the given word of the day is not hinted at in any way – the dotted squares merely represent the range of word sizes. This is also explained in the how-to-play section, where using larger words is encouraged as a strategy :)
